### PR TITLE
do not crash if voteLog is not found

### PR DESCRIPTION
**Pull request by barisusakli**
Was getting this crash with this plugin
2018-03-06T18:03:21.374Z [29120] - ^[[31merror^[[39m:  TypeError: Cannot read property 'amount' of null
   at /node_modules/nodebb-plugin-reputation-rules/library.js:222:29

### CODE REVIEW

**Comment by exomarty** [comment]
:)

**Comment by TheBronx** [comment]
Thanks for the PR @barisusakli 
If I can remember how this plugin works, the error you just fixed would happen when undoing a vote that was casted before activating the plugin.
That's definitely an scenario I didn't consider, in fact there is another "plugin" to reset all the votes and reputation to avoid this: https://github.com/exo-do/nodebb-reset-reputation

It is clearly a bug, but bear in mind that activating the plugin when previous votes are already casted on your board might be a bit weird. It won't crash now (I hope :smile: ), but mixing "normal" votes with "super powered" votes will be a bit strange unless you explain it to the users.

Just wanted to clarify that, activating without resetting reputation was not the plan when developing the plugin. Not a big deal.

Thank you for taking the time to fix it, appreciated :smiley:

**Comment by TheBronx** [comment]
_released to npm as **v1.1.3**_

**Comment by barisusakli** [comment]
Thanks 👍

**Pull request merged**
